### ISSUE TITLE
Satellite identification number in gnss-monitoring-ds nodes is unclear

### ISSUE THREAD

**Issue by andrewrscott** [SMPTE/rp2059-15#11]
There are three instances in the YANG model where a satellite ID number is described as a "PRN ID" with these possible uint16 values:
        	  1-32 GPS
        	  33-54 various Satellite Based Augmentation Systems (SBAS) [EGNOS, WAAS, SDCM, GAGAN, MSAS]
        	  55-64 not used
        	  65-96 GLONASS
        	  97-119 not used
        	  120-151 SNAS PRN
        	  152-158 various Satellite Based Augmentation Systems (SBAS) [EGNOS, WAAS, SDCM, GAGAN, MSAS]
        	  159-172 not used
        	  173-182 Indoor Messaging System (IMES)
        	  193-200 QZSS
        	  201-205 Beidou (u-blox, not NMEA)
        	  301-336 GALILEO
        	  401-437 Beidou (NMEA)
It is unclear where these numbers come from.  It appears to be an extension of the gpsd documentation (https://gpsd.gitlab.io/gpsd/gpsd_json.html) , which only says: "PRN ID of the satellite. 1-63 are GNSS satellites, 64-96 are GLONASS satellites, 100-164 are SBAS satellites"

However, these numbers don't easily match to real-life numbering.  Galileo and BeiDou appear to use alphanumeric values (e.g. "E01" and "C01") for their respective PRN IDs, and GLONASS uses numbers not labelled "PRN" and not in the 65-96 range. See https://www.gpsworld.com/the-almanac/.

**Comment by psaungsomboon** [comment]
The proposal is to consolidate the three PRN references into a single tree adopt this System ID and Signal ID arrangement:
https://gpsd.gitlab.io/gpsd/NMEA.html#_nmea_4_11_system_id_and_signal_id

The data model will drop any u-blox specifics, and any native GNSS chipset output shall be converted to the standardized GNSS ID, System ID and Signal ID required by RB 2059-15

**Comment by psaungsomboon** [comment]
Resolved in PCD2 as per the proposed change.
