### ISSUE TITLE
Redundant structure of gnss-monitoring-ds container

### ISSUE THREAD

**Issue by andrewrscott** [SMPTE/rp2059-15#12]
The gnss-monitoring-ds container has several nodes that are redundant or have no obvious use:

1. sky-object-ds has a "class" leaf node that is hard-coded to the string "SKY".  I presume this is to indicate that the data set is related to the SKY object from gpsd (https://gpsd.gitlab.io/gpsd/gpsd_json.html) but since the YANG object already deviates from the gpsd object, there is no apparent need to include the "class" value. 
2. Similarly, the osc-object-ds container has a "class" node set to "OSC".  This relation to the gpsd object could also be explained in the description field and does not need to be a static leaf node in the YANG model.
3. sky-object-ds has a "satellite-list" that is only a list of satellite PRN ID numbers (called "key-field" here) and nothing else.  There is a separate satellite-object-ds that repeats the same list of ID numbers (now called "prn") along with other useful data like signal strength etc.  In the original gpsd object, this array is part of the SKY object. There is a third list, in constellation-status-ds, also indexed by the satellite PRN number.  I recommend merging the three satellite lists into a single list under the sky-object-ds.  This is closer in structure to the gpsd response.

**Comment by psaungsomboon** [comment]
class: 'SKY' and 'OSC' will be removed from the data model.
The other comments will be addressed in a larger restructuring of the (to be renamed) gnss-ds container in comment #11

**Comment by psaungsomboon** [comment]
Resolved in PCD2 as part of the changes to the gnss container
