### ISSUE TITLE
SMPTE management messages are not IEEE compliant

### ISSUE THREAD

**Issue by kierank** [SMPTE/rp2059-15#13]
Do you plan to address this issue? At the least it would be nice to understand if endpoints are behaving badly as a result without tcpdump and before it's flooding.

It causes a LOT of issues in the field. More info here:
https://sourceforge.net/p/linuxptp/mailman/message/36877704/

**Comment by psaungsomboon** [comment]
Kieran - many thanks for your comment.
We believe that this is out of scope for the RP and the Data Model, and therefore plan to make no changes based on this comment.
We will however pass your observations back to the document editor of ST 2059-2

**Comment by kierank** [comment]
lol

**Comment by kierank** [comment]
If a receiver could report the number of TLV multicast management messages it receives that would help diagnose SMPTE TLV floods that happen a lot.
